application: ca-gcp-developer
runtime: python27
api_version: 1
threadsafe: true
version: v1

handlers:
  - url: /_ah/spi/.*
    script: ep.app

  - url: /.*
    script: main.app

libraries:
  - name: endpoints
    version: 1.0

skip_files:
  - venv/.*
  - ^(.*/)?.*\.py[co]$
